# Generated by Django 3.2 on 2023-10-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_fhone_client_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='diection',
            new_name='address',
        ),
    ]
