# Generated by Django 3.2 on 2023-10-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_diection_client_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='birthday_date',
            new_name='birthdate',
        ),
    ]
